export interface IkmType {
    id: number;
    nama_perusahaan: string;
    nama_pemilik: string;
    alamat: string;
    kelurahan_id: number;
    kecamatan_id: number;
    kabupaten_id: number;
    provinsi_id: number;
    kontak_person?: string;
    no_hp?: string;
    email?: string;
    nomor_izin?: string;
    tahun_izin?: number;
    tahun_data: number;
    tenaga_kerja_pria: number;
    tenaga_kerja_wanita: number;
    nilai_investasi: number;
    nilai_kapasitas: number;
    satuan_kapasitas: string;
    nilai_produksi: number;
    nilai_bahan_baku: number;
    status_ekspor: boolean;
    negara_tujuan_ekspor?: string;
    status_aktif: boolean;
    jenis_pembiayaan?: string;
    created_at: string;
    updated_at: string;
    typeproducts?: Array<{id: number, name: string}>;
    typeindustries?: Array<{id: number, name: string}>;
    provinsi?: {id: number, name: string};
    kabupaten?: {id: number, name: string}; 
    kecamatan?: {id: number, name: string};
    kelurahan?: {id: number, name: string};
}